data:
    dataset: "human36m"
    dataset_path: "./data/data_3d_h36m.npz"
    dataset_path_train_2d: "./data/data_2d_h36m_gt_gmm.npz"
    dataset_path_test_2d: "./data/data_2d_h36m_gt_gmm.npz"
    num_joints: 17
    num_workers: 32

model:
    hid_dim: 96
    emd_dim: 96
    coords_dim: [5,5]
    num_layer: 5
    n_head: 4
    dropout: 0.25
    n_pts: 17
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True
    var_type: fixedsmall

# Adaptive implicit configuration - optimized parameters
implicit:
    solver: "anderson"         # Anderson acceleration is generally faster
    max_iterations: 10         # Reduced from 20 to improve speed
    tolerance: 0.0001          # Relaxed from 1e-5 to reduce iterations
    
    # Anderson acceleration parameters - optimized
    anderson_m: 3              # Reduced history size for faster computation
    anderson_beta: 1.0         # No damping for faster convergence
    anderson_lambda: 0.0001    # Regularization for numerical stability
    
    # Adaptive features - optimized
    use_adaptive_alpha: true   # Keep adaptive relaxation
    init_alpha: 0.7            # Higher initial relaxation for faster convergence
    min_alpha: 0.2             # Increased from 0.1
    max_alpha: 0.9             # Keep maximum relaxation
    
    use_progressive_tol: true  # Use progressive tolerance
    init_tol: 0.01             # Start with a looser tolerance (was 0.001)
    final_tol: 0.0001          # Looser final tolerance (was 1e-5)
    tol_decay_steps: 5000      # Keep same decay steps
    
    use_warm_start: true       # Essential for speed
    warm_start_momentum: 0.9   # Keep momentum factor

# Keep diffusion parameters for compatibility
diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.001
    num_diffusion_timesteps: 51

# Match original DiffPose training parameters
training:
    batch_size: 1024           # Match original DiffPose (increased from 256)
    n_epochs: 80
    n_iters: 5000000
    snapshot_freq: 5000
    validation_freq: 2000
    num_workers: 32            # Match original DiffPose

# Test parameters - optimized
testing:
    test_times: 1              # Match original DiffPose (was 5)
    test_timesteps: 2          # Match original DiffPose
    test_num_diffusion_timesteps: 12  # Match original DiffPose
    track_time: true
    track_memory: true

optim:
    decay: 60
    optimizer: "Adam"
    lr: 0.00002                # Match original DiffPose
    lr_gamma: 0.9
    amsgrad: false
    eps: 0.00000001
    grad_clip: 1.0